DECLARE @TANGGAL VARCHAR(8)
DECLARE @POSISI VARCHAR(8)
DECLARE @POSISI_STRIPPED VARCHAR(10)
SET @TANGGAL = CONVERT(VARCHAR, GETDATE(), 112)
SET @POSISI = CONVERT(VARCHAR, DATEADD(DAY, -1, @TANGGAL), 112)
SET @POSISI_STRIPPED = CONVERT(VARCHAR, DATEADD(DAY, -1, @TANGGAL), 120)
EXEC('
WITH LNMAST_DEDUPLICATION AS (
    SELECT *
    FROM (
        SELECT 
            LNMAST.ACCOUNTNUMBER
            , LNMAST.LOANTYPE
            , LNMAST.CIFNUM
            , LNMAST.CIFNUMOLD
            , LNMAST.CBAL
            , LNMAST.OPENDAT6
            , LNMAST.DISBURSEMENTDATE6
            , LNMAST.MATURITYDATE6
            , LNMAST.NEXTBILLINGISSUED6
			, LNMAST.NEXTACCRUEDATE6
            , LNMAST.CLOSINGDATE6
            , LNMAST.STATUS
            , LNMAST.PVARCODE
            , LNMAST.PVAR
            , LNMAST.RATE
            , LNMAST.FACTYPE
            , LNMAST.REFERENCE
            , LNMAST.SHORTNAME
            , LNMAST.HOLD
            , LNMAST.PRINCIPALAMOUNT
            , LNMAST.CURRENCY
            , LNMAST.PERIOD
            , LNMAST.PERIODMODE
            , LNMAST.DATETRANSFER
            , LNMAST.ACCRUE
            , LNMAST.TODACR
            , LNMAST.PENALTYRATE
            , LNMAST.ABAL
            , LNMAST.FLAG_RESTRUK
            , LNMAST.REPAYMENTSETTLEMENTACCOUNT
            , LNMAST.ANGSURAN
            , LNMAST.DEFRATE
            , LNMAST.DEFACCRUE
            , LNMAST.TRANSFERFROM
            , LNMAST.TRANSFERTO
            -- , SUBSIDI_ACCRUE
            -- , SUBSIDI_ADD_ACCRUE
            -- , SUBSIDI_ADD_RATE
            , ROW_NUMBER() OVER(
                PARTITION BY 
                    CIFNUM
                    , OPENDAT6 
                ORDER BY 
                    CAST(CBAL AS DECIMAL(21,2)) DESC
                    , COALESCE(CLOSINGDATE7, ''9999999'') DESC
            ) AS RN
            , COUNT(*) OVER(PARTITION BY CIFNUM, OPENDAT6)-1 AS DB_DUPLICATE_ACCNO_COUNT
        FROM DWH_ABCS_M_LNMAST..ABCS_M_LNMAST_'+@TANGGAL+' AS LNMAST

    ) X 
    -- WHERE RN = 1 --OR TRANSFERTO IS NULL
) 
, BASE_ATRIBUSI_PERFORMA AS (
    SELECT 
        CAST('''+@POSISI_STRIPPED+''' AS DATE) AS POSISI

        , LNMAST.ACCOUNTNUMBER
        , LNMAST.CIFNUM
        , LNAPPF.NO_FASILITAS
        
        , CAST(LNMAST.CBAL AS DECIMAL(22,3)) AS OUTSTANDING
        , CAST(LNMAST.PRINCIPALAMOUNT AS DECIMAL(22,0)) AS PLAFOND
        , CAST(LNMAST.HOLD AS DECIMAL(22,3)) AS HOLD
        , CAST(LNMAST.ABAL AS DECIMAL(22,3)) AS ADVANCED_BALANCE
        , LNMAST.STATUS AS ACCOUNTSTATUS
        , LNMAST.FLAG_RESTRUK 
        -- , ''L'' AS PRODUCTTYPE
        , LNMAST.LOANTYPE
        , LNPAR2.DESCRIPTION AS LOANPRODUCTNAME
        , LNMAST.FACTYPE

        , CAST(DWH_BIGDATA.dbo.DATE6_TO_DATE(LNMAST.OPENDAT6) AS DATE) AS OPENDATE
        , CAST(DWH_BIGDATA.dbo.DATE6_TO_DATE(LNMAST.DISBURSEMENTDATE6) AS DATE) AS DISBURSEMENTDATE
        , CAST(DWH_BIGDATA.dbo.DATE6_TO_DATE(LNMAST.MATURITYDATE6) AS DATE) AS MATURITYDATE
        , CAST(DWH_BIGDATA.dbo.DATE6_TO_DATE(LNMAST.CLOSINGDATE6) AS DATE) AS CLOSINGDATE
        , CAST(DWH_BIGDATA.dbo.DATE6_TO_DATE(LNAPPF.TGL_AKAD_AKHIR) AS DATE) AS TGL_AKAD_AKHIR
        
        , LNAPPF.NO_URUT_FASILITAS
        , LNAPPF.PROGRAM
        , MJP.DESKRIPSI AS JENIS_PENGGUNAAN
        , LNAPPF.SEKTOR_EKONOMI AS KODE_SEKTOR_EKONOMI
        , SEK.SEKTOR_EKONOMI
        , ESS.SUB_SECTOR_NAME AS NAMA_SUB_SEKTOR_EKONOMI
        
        , UPPER(LNMAST.SHORTNAME) AS CUSTNAME
        , CFMAST.NO_ID AS NIK
        , CFMAST.NO_HP
        , CASE 
            WHEN CFMAST.JENIS_NASABAH_TERKAIT = ''Y'' THEN ''1'' 
            ELSE ''2'' 
        END AS FLAG_TERKAIT
        , CFMAST.FAKTOR_RESIKO
        , LNAPPF.SEGMENTASI_KREDIT
        , LNAPPF.KETERANGAN_COVID
        
        , D.BRCODE AS KODE_UKER
        , D.BRNAME AS UNIT_KERJA
        , LNAPPF.AO_PEMRAKARSA AS USERID_AO_PEMRAKARSA
        , B1.USERNAME AS NAMA_AO_PEMRAKARSA
        , PN_PENGELOLA_GABUNG.PN_AO_PENGELOLA_GABUNG AS PN_AO_PENGELOLA
        , EMP.FULLNAME AS NAMA_AO_PENGELOLA 
        , LNAPPF.AO_BOOKINGOFFICE AS USERID_AO_BOOKING_OFFICE
        , B2.USERNAME AS NAMA_AO_BOOKING_OFFICE

        , LNMAST.REPAYMENTSETTLEMENTACCOUNT
        
        , LNMAST.ANGSURAN
        
        , CAST(DWH_BIGDATA.dbo.DATE6_TO_DATE(LNMAST.NEXTBILLINGISSUED6) AS DATE) AS NEXTBILLINGISSUED
		, CAST(DWH_BIGDATA.dbo.DATE6_TO_DATE(LNMAST.NEXTACCRUEDATE6) AS DATE) AS NEXTACCRUEDATE
        , LNBICD.KOLEK
        , LNBICD.DAYSKOLEK AS UMURTUNGGAKAN
        , CAST(BILL.PRINCIPALAMOUNTBILL AS DECIMAL(19,3)) AS TUNGGAKAN_POKOK
        , CAST(BILL.INTERESTAMOUNTBILL AS DECIMAL(19,3)) AS TUNGGAKAN_BUNGA
        , CAST(BILL.PENALTYAMOUNTBILL AS DECIMAL(19,3)) AS DENDA
        , CAST(BILL.INTERESTAMOUNTPAID AS DECIMAL(19,3)) AS INT_PAID
        
        , LNMAST.CURRENCY
        , CASE 
            WHEN LNMAST.PVARCODE = ''+'' THEN (CAST(LNMAST.RATE AS FLOAT) + CAST(LNMAST.PVAR AS FLOAT)) 
            ELSE (CAST(LNMAST.RATE AS FLOAT) - CAST(LNMAST.PVAR AS FLOAT)) 
        END AS RATEMAIN
        , LNMAST.RATE
        , LNMAST.PVAR
        , LNMAST.PVARCODE
        , LNMAST.PERIOD
        , LNMAST.PERIODMODE
        , LNMAST.PENALTYRATE
        , LNMAST.ACCRUE
        , LNMAST.TODACR
        , LNMAST.DEFRATE
        , LNMAST.DEFACCRUE

        , LNPAR2.LOANTYPEOLD
        , LNMAST.CIFNUMOLD + ''.'' + LNMAST.FACTYPE + ''.'' + SUBSTRING(LNMAST.REFERENCE, 21, 3) AS NO_FASILITAS_LAMA
        
        , LNMAST.TRANSFERFROM AS NO_REKENING_TOB_FROM
        , LNMAST.TRANSFERTO AS NO_REKENING_TOB_TO
        , LNMAST.DATETRANSFER AS DATE_TOB
        
        , DB_DUPLICATE_ACCNO_COUNT
        , PARTNERSHIPS.NAME AS PARTNER
        , LNMAST.RN
		, RM.NAMA_AO_PRAKARSA_UPDATE
    FROM LNMAST_DEDUPLICATION LNMAST
    LEFT JOIN DWH_ABCS_P_LNPAR2..ABCS_P_LNPAR2 AS LNPAR2 ON LNMAST.LOANTYPE = LNPAR2.LOANTYPE 
    LEFT JOIN DWH_ABCS_M_CFMAST..ABCS_M_CFMAST_'+@TANGGAL+' AS CFMAST ON LNMAST.CIFNUM = CFMAST.CIFNUM 
    LEFT JOIN DWH_ABCS_P_JHDATA..ABCS_P_JHDATA AS D ON SUBSTRING(LNMAST.ACCOUNTNUMBER, 1, 4) = D.BRCODE 
    LEFT JOIN DWH_ABCS_M_LNBICD..ABCS_M_LNBICD_'+@TANGGAL+' AS LNBICD ON LNMAST.ACCOUNTNUMBER = LNBICD.ACCOUNTNUMBER 
    LEFT JOIN DWH_ABCS_M_LNAPPF..ABCS_M_LNAPPF_'+@TANGGAL+' AS LNAPPF ON LNMAST.REFERENCE = LNAPPF.NO_FASILITAS 
    LEFT JOIN [AGRODWH].[dbo].[SEKTOR_EKONOMI_UPLOAD] AS SEK ON LNAPPF.SEKTOR_EKONOMI = SEK.KODE
    LEFT JOIN DWH_BRANCHUSERPROFILE..BRANCHUSERPROFILE_'+@TANGGAL+' B1 ON B1.USERID = LNAPPF.AO_PEMRAKARSA 
    LEFT JOIN DWH_BRANCHUSERPROFILE..BRANCHUSERPROFILE_'+@TANGGAL+' B2 ON B2.USERID = LNAPPF.AO_BOOKINGOFFICE 
	LEFT JOIN [10.69.7.63].PINANGMIKRO.dbo.automation_loan_accounts AS AUTO ON LNMAST.ACCOUNTNUMBER = AUTO.LOAN_ACCOUNT_NUMBER 
	LEFT JOIN [10.69.7.63].PINANGMIKRO.dbo.PRAKARSA AS PRAKARSA ON PRAKARSA.ID = AUTO.PRAKARSA_ID
	LEFT JOIN (
		SELECT LNAPPF.AO_PEMRAKARSA AS USERID_AO_PEMRAKARSA,
		CASE 
			when B1.USERNAME is not null then B1.USERNAME
			when B1.USERNAME is null and emp.fullname is not null then emp.fullname  
		END as NAMA_AO_PRAKARSA_UPDATE
		FROM LNMAST_DEDUPLICATION LNMAST
		LEFT JOIN DWH_ABCS_M_LNAPPF..ABCS_M_LNAPPF_'+@TANGGAL+' AS LNAPPF ON LNMAST.REFERENCE = LNAPPF.NO_FASILITAS 
		LEFT JOIN DWH_BRANCHUSERPROFILE..BRANCHUSERPROFILE_'+@TANGGAL+' B1 ON B1.USERID = LNAPPF.AO_PEMRAKARSA
		LEFT JOIN [10.69.7.63].PINANGMIKRO.dbo.EMPLOYEES as EMP on EMP.personal_number = LNAPPF.AO_PEMRAKARSA
	) RM ON RM.USERID_AO_PEMRAKARSA = LNAPPF.AO_PEMRAKARSA
	LEFT JOIN(
		SELECT PN_PENGELOLA.ACCOUNTNUMBER,
		CASE
			 WHEN PN_PENGELOLA.PN_AO_PENGELOLA_HRD IS NOT NULL THEN PN_PENGELOLA.PN_AO_PENGELOLA_HRD
			 WHEN PN_PENGELOLA.PN_AO_PENGELOLA_HRD IS NULL AND PN_PENGELOLA.USER_ID IS NOT NULL THEN PN_PENGELOLA.USER_ID 
			 ELSE NULL END AS PN_AO_PENGELOLA_GABUNG 				
		FROM(
			SELECT LNMAST.ACCOUNTNUMBER,PRAKARSA.USER_ID 
				,CASE
	            WHEN PN.EMPLOYEEID IS NOT NULL THEN PN.EMPLOYEEID
	            WHEN PN.EMPLOYEEID IS NULL AND PN2.EMPLOYEEID IS NOT NULL THEN PN2.EMPLOYEEID
	            ELSE NULL 
	        	END AS PN_AO_PENGELOLA_HRD
			FROM LNMAST_DEDUPLICATION LNMAST
			LEFT JOIN DWH_ABCS_P_LNPAR2..ABCS_P_LNPAR2 AS LNPAR2 ON LNMAST.LOANTYPE = LNPAR2.LOANTYPE 
			LEFT JOIN DWH_ABCS_M_LNAPPF..ABCS_M_LNAPPF_'+@TANGGAL+' AS LNAPPF ON LNMAST.REFERENCE = LNAPPF.NO_FASILITAS 
			LEFT JOIN DWH_BRANCHUSERPROFILE..BRANCHUSERPROFILE_'+@TANGGAL+' B3 ON B3.USERID = LNAPPF.AO_PENGELOLA 
			LEFT JOIN [172.31.1.92].[HRD].[dbo].[EMPLOYEE] AS PN ON B3.UserCode = PN.EMPLOYEEID 
			LEFT JOIN [172.31.1.92].[HRD].[dbo].[EMPLOYEE] AS PN2 ON RTRIM(LTRIM(UPPER(B3.USERNAME))) = RTRIM(LTRIM(UPPER(PN2.EMPLOYEENAME)))
			LEFT JOIN [10.69.7.63].PINANGMIKRO.dbo.automation_loan_accounts AS AUTO ON LNMAST.ACCOUNTNUMBER = AUTO.LOAN_ACCOUNT_NUMBER
			LEFT JOIN [10.69.7.63].PINANGMIKRO.dbo.PRAKARSA AS PRAKARSA ON PRAKARSA.ID = AUTO.PRAKARSA_ID
			) AS PN_PENGELOLA
		) AS PN_PENGELOLA_GABUNG ON PN_PENGELOLA_GABUNG.ACCOUNTNUMBER = LNMAST.ACCOUNTNUMBER   
	LEFT JOIN [10.69.7.63].PINANGMIKRO.dbo.EMPLOYEES AS EMP ON PN_PENGELOLA_GABUNG.PN_AO_PENGELOLA_GABUNG = EMP.personal_number
	--LEFT JOIN [10.69.7.63].PINANGMIKRO.dbo.EMPLOYEES AS EMP ON PN_PENGELOLA.PN_AO_PENGELOLA = EMP.personal_number
	LEFT JOIN [10.69.7.63].PINANGMIKRO.dbo.BUSINESS AS BUSINESS ON BUSINESS.PRAKARSA_ID = AUTO.PRAKARSA_ID
	LEFT JOIN [10.69.7.63].PINANGMIKRO.dbo.PARTNERSHIPS AS PARTNERSHIPS ON PARTNERSHIPS.ID = BUSINESS.PARTNERSHIP_ID
    LEFT JOIN AGRODWH.DBO.DWH_PINANG_MIKRO_SUB_SECTOR AS ESS on ESS.ID = BUSINESS.SUB_ECONOMIC_SECTOR
    LEFT JOIN [AGROBANKAPP_DWH].[dbo].[M_JENIS_PENGGUNAAN] MJP ON LNAPPF.JENIS_PENGGUNAAN = MJP.KODE
    LEFT JOIN (
        SELECT ACCOUNTNUMBER, SUM(CAST(PRINCIPALAMOUNTBILL AS FLOAT) - CAST(PRINCIPALAMOUNTPAID AS FLOAT)) as PRINCIPALAMOUNTBILL, 
        SUM(CAST (INTERESTAMOUNTBILL AS FLOAT) - CAST (INTERESTAMOUNTPAID AS FLOAT)) as INTERESTAMOUNTBILL, 
        SUM(CAST(PENALTYAMOUNTBILL AS FLOAT) - CAST(PENALTYAMOUNTPAID AS FLOAT)) as PENALTYAMOUNTBILL, SUM(CAST(INTERESTAMOUNTPAID AS FLOAT)) as INTERESTAMOUNTPAID 
        FROM DWH_ABCS_T_LNBILL..ABCS_T_LNBILL_'+@TANGGAL+'
        GROUP BY ACCOUNTNUMBER
    ) AS BILL ON BILL.ACCOUNTNUMBER = LNMAST.ACCOUNTNUMBER 
    WHERE 1=1
        -- AND (LNMAST.STATUS = ''1'' OR LNMAST.STATUS IN (''1'', ''3''))
        AND ( -- PERFORMA
            LNMAST.LOANTYPE IN (''40002'', ''40003'') --, ''40004'')
           -- AND LNAPPF.SEGMENTASI_KREDIT = ''400''
        )
)
, RESULT AS (
    SELECT DISTINCT *
    FROM BASE_ATRIBUSI_PERFORMA
)
--Atribusi All
--INSERT INTO [AGRODWH].[dbo].[DASHBOARD_PERFORMA_ATRIBUSI_PENCAPAIAN_ALL_PERHARI]
SELECT *
--INTO [AGRODWH].[dbo].[DASHBOARD_PERFORMA_ATRIBUSI_PENCAPAIAN_ALL_PERHARI]x`
FROM RESULT
')